version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000 -- optional, your user id
      PGID: 1000 -- optional, your group id
    ports:
      - 3000:3000
    volumes:
      # Make sure your local config directory exists
      - /homepage/config:/app/config
      # optional, for docker integrations
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    restart: unless-stopped