version: "3.7"

# Reference https://github.com/tailscale-dev/docker-guide-code-examples/blob/main/01-authkey/compose.yaml
services:
  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:latest
    hostname: pi-tailscale
    environment:
      - TS_AUTHKEY=
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ~/tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  nginx-authkey-test:
    image: nginx
    network_mode: service:tailscale